-- MySQL Script generated by MySQL Workbench
-- Sat Dec 21 23:06:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`descriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`descriptions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descriptionscol` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rooms` (
  `number` INT(11) NOT NULL,
  `room_class` VARCHAR(10) NOT NULL,
  `sits` INT(11) NOT NULL,
  `price` DECIMAL(10,0) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role_id` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_in` DATETIME NOT NULL,
  `date_out` DATETIME NOT NULL,
  `user_id` INT(11) NOT NULL,
  `room_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `room`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`reserved`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserved` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `room_id` INT(11) NOT NULL,
  `date_in` DATETIME NOT NULL,
  `date_out` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`room_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room_class` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`rooms-descriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rooms-descriptions` (
  `room_id` INT(11) NOT NULL,
  `descriptions_id` INT(11) NOT NULL,
  CONSTRAINT ` rooms-descriptions_description`
    FOREIGN KEY (`descriptions_id`)
    REFERENCES `mydb`.`descriptions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `room-descriptions_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`rooms`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`rooms` (`number`, `room_class`, `sits`, `price`, `id`) VALUES (2, 'А', 1, 60, 18);
INSERT INTO `mydb`.`rooms` (`number`, `room_class`, `sits`, `price`, `id`) VALUES (3, 'A', 3, 90, 19);
INSERT INTO `mydb`.`rooms` (`number`, `room_class`, `sits`, `price`, `id`) VALUES (4, 'D', 2, 40, 28);
INSERT INTO `mydb`.`rooms` (`number`, `room_class`, `sits`, `price`, `id`) VALUES (5, 'B', 1, 50, 29);
INSERT INTO `mydb`.`rooms` (`number`, `room_class`, `sits`, `price`, `id`) VALUES (8, 'A', 2, 22, 31);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`role`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`role` (`id`, `role_name`) VALUES (1, 'user');
INSERT INTO `mydb`.`role` (`id`, `role_name`) VALUES (2, 'administration');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`user` (`id`, `name`, `surname`, `password`, `role_id`, `email`) VALUES (1, 'Eugene', 'Korenevsky', 'kara', 1, 'kara-91@tut.by');
INSERT INTO `mydb`.`user` (`id`, `name`, `surname`, `password`, `role_id`, `email`) VALUES (2, 'Olga', 'Kinevich', 'kina', 2, 'olga@tut.by');
INSERT INTO `mydb`.`user` (`id`, `name`, `surname`, `password`, `role_id`, `email`) VALUES (10, 'Ivan', 'Ivanova', 'ivan', 1, 'ivansddd@tut.by');
INSERT INTO `mydb`.`user` (`id`, `name`, `surname`, `password`, `role_id`, `email`) VALUES (11, 'Peter', 'Petrov', 'peter', 1, 'peter@tut.by');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`order`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`order` (`id`, `date_in`, `date_out`, `user_id`, `room_id`) VALUES (16, '2019-12-23 20:20:00', '2019-12-31 20:20:00', 1, 28);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`reserved`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`reserved` (`id`, `user_id`, `room_id`, `date_in`, `date_out`) VALUES (43, 1, 18, '2019-12-20 22:22:00', '2019-12-26 22:22:00');
INSERT INTO `mydb`.`reserved` (`id`, `user_id`, `room_id`, `date_in`, `date_out`) VALUES (45, 1, 19, '2019-12-23 20:20:00', '2019-12-26 20:20:00');
INSERT INTO `mydb`.`reserved` (`id`, `user_id`, `room_id`, `date_in`, `date_out`) VALUES (46, 1, 31, '2019-12-25 20:20:00', '2019-12-31 20:20:00');
INSERT INTO `mydb`.`reserved` (`id`, `user_id`, `room_id`, `date_in`, `date_out`) VALUES (48, 1, 28, '2019-12-21 20:20:00', '2019-12-25 20:20:00');

COMMIT;

